version: '3.2'

services:
  database:
    image: mariadb:10
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - database:/var/lib/mysql

  http:
    image: nginx:1-alpine
    depends_on:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro
    ports:
      - "80:80"

  php:
    build:
      context: ./docker/php
    working_dir: /srv
    volumes:
      - ./:/srv/

  node:
    build:
      context: ./docker/node
    working_dir: /srv
    volumes:
      - ./:/srv/

  h2-proxy:
    build:
      context: ./docker/h2-proxy
    depends_on:
      - http
    ports:
      - "443:443"

volumes:
  database: ~
